name: Greeting from Theodore Fabian Rudy
on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

    workflow_dispatch:

        
jobs:
    build:
        name: My Job
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Print a greeting
          env:
            MY_VAR: Hi there! My name is
            FIRST_NAME: Theodore
            MIDDLE_NAME: Fabian
            LAST_NAME: Rudy
          run: |
            echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
